"""update articles table for rag

Revision ID: 39af96db7d5b
Revises: 6e8326fb12b2
Create Date: 2026-04-26 19:05:20.516972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39af96db7d5b'
down_revision: Union[str, Sequence[str], None] = '6e8326fb12b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('arxiv_id', sa.String(length=255), nullable=False))
    op.add_column('articles', sa.Column('title', sa.String(length=500), nullable=False))
    op.add_column('articles', sa.Column('authors', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('articles', sa.Column('query', sa.Text(), nullable=True))
    op.create_index(op.f('ix_articles_arxiv_id'), 'articles', ['arxiv_id'], unique=False)
    op.drop_column('articles', 'url')
    op.drop_column('articles', 'updated_at')
    op.drop_column('articles', 'name')
    op.drop_column('articles', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('articles', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_articles_arxiv_id'), table_name='articles')
    op.drop_column('articles', 'query')
    op.drop_column('articles', 'score')
    op.drop_column('articles', 'authors')
    op.drop_column('articles', 'title')
    op.drop_column('articles', 'arxiv_id')
    # ### end Alembic commands ###
