"""empty message

Revision ID: 6e8326fb12b2
Revises: 6bead19dc6eb
Create Date: 2026-01-08 22:58:20.777099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6e8326fb12b2'
down_revision: Union[str, Sequence[str], None] = '6bead19dc6eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала создаём notebooks (так как на неё ссылаются files и articles)
    op.create_table('notebooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebooks_id'), 'notebooks', ['id'], unique=False)
    op.create_index(op.f('ix_notebooks_user_id'), 'notebooks', ['user_id'], unique=False)
    op.create_foreign_key('fk_notebooks_user_id', 'notebooks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    # Затем files
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notebook_id', sa.UUID(), nullable=False),
    sa.Column('upload_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_notebook_id'), 'files', ['notebook_id'], unique=False)
    op.create_foreign_key('fk_files_notebook_id', 'files', 'notebooks', ['notebook_id'], ['id'], ondelete='CASCADE')
    
    # Затем articles
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('notebook_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_index(op.f('ix_articles_notebook_id'), 'articles', ['notebook_id'], unique=False)
    op.create_foreign_key('fk_articles_notebook_id', 'articles', 'notebooks', ['notebook_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_articles_notebook_id', 'articles', type_='foreignkey')
    op.drop_index(op.f('ix_articles_notebook_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_table('articles')
    
    op.drop_constraint('fk_notebooks_user_id', 'notebooks', type_='foreignkey')
    op.drop_index(op.f('ix_notebooks_user_id'), table_name='notebooks')
    op.drop_index(op.f('ix_notebooks_id'), table_name='notebooks')
    op.drop_table('notebooks')
    
    op.drop_constraint('fk_files_notebook_id', 'files', type_='foreignkey')
    op.drop_index(op.f('ix_files_notebook_id'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
