"""areas tags shares sources chat notes user notif_settings

Revision ID: e0f0d3f4d3e9
Revises: 39af96db7d5b
Create Date: 2026-05-26 16:07:24.388177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0f0d3f4d3e9'
down_revision: Union[str, Sequence[str], None] = '39af96db7d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('palette_key', sa.String(length=16), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('areas_user_active_ix', 'areas', ['user_id'], unique=False, postgresql_where=sa.text('archived_at IS NULL'))
    op.create_index('areas_user_slug_active_uq', 'areas', ['user_id', 'slug'], unique=True, postgresql_where=sa.text('archived_at IS NULL'))
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slug', name='tags_user_slug_uq')
    )
    op.create_table('notebook_chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notebook_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='notebook_chat_messages_role_check'),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('notebook_chat_messages_nb_ix', 'notebook_chat_messages', ['notebook_id', 'created_at'], unique=False)
    op.create_table('notebook_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notebook_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), server_default='', nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('notebook_notes_nb_ix', 'notebook_notes', ['notebook_id', 'updated_at'], unique=False)
    op.create_table('notebook_shares',
    sa.Column('notebook_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), server_default='viewer', nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('viewer', 'commenter', 'editor')", name='notebook_shares_role_check'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notebook_id', 'user_id')
    )
    op.create_index('notebook_shares_user_ix', 'notebook_shares', ['user_id'], unique=False)
    op.create_table('notebook_tags',
    sa.Column('notebook_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notebook_id', 'tag_id')
    )
    op.create_index('notebook_tags_tag_ix', 'notebook_tags', ['tag_id'], unique=False)
    op.create_table('notebook_sources',
    sa.Column('notebook_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('selected', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notebook_id', 'article_id')
    )
    op.add_column('notebooks', sa.Column('area_id', sa.UUID(), nullable=True))
    op.add_column('notebooks', sa.Column('visibility', sa.String(length=16), server_default='private', nullable=False))
    op.create_foreign_key(
        'notebooks_area_id_fkey',
        'notebooks', 'areas',
        ['area_id'], ['id'],
        ondelete='SET NULL',
    )
    op.create_check_constraint(
        'notebooks_visibility_check',
        'notebooks',
        "visibility IN ('private', 'shared', 'public')",
    )
    op.add_column('users', sa.Column('notif_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"digest_weekly": true, "new_citations": true, "shared_activity": false}\'::jsonb'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notif_settings')
    op.drop_constraint('notebooks_visibility_check', 'notebooks', type_='check')
    op.drop_constraint('notebooks_area_id_fkey', 'notebooks', type_='foreignkey')
    op.drop_column('notebooks', 'visibility')
    op.drop_column('notebooks', 'area_id')
    op.drop_table('notebook_sources')
    op.drop_index('notebook_tags_tag_ix', table_name='notebook_tags')
    op.drop_table('notebook_tags')
    op.drop_index('notebook_shares_user_ix', table_name='notebook_shares')
    op.drop_table('notebook_shares')
    op.drop_index('notebook_notes_nb_ix', table_name='notebook_notes')
    op.drop_table('notebook_notes')
    op.drop_index('notebook_chat_messages_nb_ix', table_name='notebook_chat_messages')
    op.drop_table('notebook_chat_messages')
    op.drop_table('tags')
    op.drop_index('areas_user_slug_active_uq', table_name='areas', postgresql_where=sa.text('archived_at IS NULL'))
    op.drop_index('areas_user_active_ix', table_name='areas', postgresql_where=sa.text('archived_at IS NULL'))
    op.drop_table('areas')
    # ### end Alembic commands ###
